definitions:
  accountcommands.CreateAccountCmdDTO:
    properties:
      email:
        type: string
      full-name:
        type: string
      password:
        type: string
      phone-number:
        type: string
      role-name:
        type: string
    type: object
  accountqueries.LoginByPhoneRequestDTO:
    properties:
      password:
        type: string
      phone-number:
        type: string
    type: object
info:
  contact: {}
  title: Authentication Service
  version: "1.0"
paths:
  /api/v1/accounts/login:
    post:
      consumes:
      - application/json
      description: login by phone number
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/accountqueries.LoginByPhoneRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: login by phone number
      tags:
      - account
  /api/v1/roles:
    get:
      consumes:
      - application/json
      description: get roles
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: get roles
      tags:
      - roles
  /external/rpc/accounts:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/accountcommands.CreateAccountCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: create account
      tags:
      - 'rpc: account'
  /ping:
    get:
      consumes:
      - application/json
      description: ping server
      produces:
      - application/json
      responses:
        "200":
          description: message success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: ping server
      tags:
      - ping
swagger: "2.0"
